### ISSUE TITLE
wo

### ISSUE THREAD

**Issue by Rockinrqt** [Idan-Neeman/Crypto-Payments-Woo#2]
I get this error when I try to update the plugin:
"Bitcoin payment gateway is not operational! Electrum Master Public Key is invalid. Must be 128 or 111 characters long, consisting of digits and letters."

I copied the key directly so I don't know what else to do.

**Comment by Idan-Neeman** [comment]
I would love to help you, could you please create a Master Public Key and publish it here so I can find out what the error is?

**Comment by Rockinrqt** [comment]
This is the Master Public Key

zpub6mf4W8jMKMKnSji6pnLV2VkhmRFSvyTio67nFwmnZNSevWkS1z7e9et5r8A7b4dxxmVZwsvR2kniT73vC3QDUnotNmEyXqroADxbEmdpYdE

**Comment by Idan-Neeman** [comment]
Ohh ok I got it :)
This plugin support xPub keys (P2PKH script type) but you try to set zPub. Please generate xPub key and it's should work well.
You can convert your zPub MPK into xPub using this [converter](https://jlopp.github.io/xpub-converter/). Please do that carefully!

**Comment by Rockinrqt** [comment]
I don't think it worked. I sent a test and it didn't go through to my wallet.

**Comment by Idan-Neeman** [comment]
Hey,
did you check before sending if the address appears on your wallet?
do you set a confirmations validation in the plugin settings?

**Comment by Rockinrqt** [comment]
how many Required Confirmations should there be?

**Comment by Idan-Neeman** [comment]
1 - by default (configurable).

**Comment by Rockinrqt** [comment]
It said that it was confirmed but it didn't go into my wallet.

**Comment by Idan-Neeman** [comment]
Do you see the transaction as approved on the WooCommerce, but can't see that in your electrum?
Are you sure that the MPK you set, is correct from your electrum? did you convert the zPub to xPub using the converter?

**Comment by Rockinrqt** [comment]
"Do you see the transaction as approved on the WooCommerce, but can't see that in your electrum?" yes
"Are you sure that the MPK you set, is correct from your electrum? did you convert the zPub to xPub using the converter?" I took the MPK from my electrum, went to the site you gave me, made sure the conversion dropdown was correct, and then converted it.

**Comment by Rockinrqt** [comment]
the plugin accepted it but the address that it gave me didn't show up in my electrum wallet. I copied it from the site and [command f] to look for it in there and it didn't show up.

**Comment by Idan-Neeman** [comment]
If the transaction marked as approved, so it's mean the plugin works well.
I guess the problem is that you put an incorrect MPK, you should check in google how to get electrum xPub MPK (maybe the converter is a bad idea).

**Comment by Rockinrqt** [comment]
wordpress says that it worked so that makes me think that I have connected to someone else's wallet.

**Comment by Idan-Neeman** [comment]
You need to create electrum wallet and choose legacy (p2pkh) as script type, not segwit...

https://preview.redd.it/2vqb45iep6n11.png?width=603&format=png&auto=webp&s=ded2617247e56113fb307e07353121610c763825

**Comment by Rockinrqt** [comment]
ok, that worked. Thanks. Can you update your instructions so this doesn't happen to other people?

**Comment by Idan-Neeman** [comment]
Yeah sure!
Thank you :)
